name: Pull Request Action
on: push
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.TOKEN }}
          pr_label: "automated pr"
          pr_title: "${{github.event.head_commit.message}}"
          pr_body: "An automated PR*"
          pr_reviewer: "PiJayson<pijay888@gmail.com>,ranz7<rdkm.korepetycje@gmail.com>,watislaf<vladkozulin@mail.ru>"
          pr_assignee: "PiJayson<pijay888@gmail.com>,ranz7<rdkm.korepetycje@gmail.com>,watislaf<vladkozulin@mail.ru>"
          pr_milestone: "End The Project"
          pr_draft: true
          pr_allow_empty: true
