name: Pull Request Action
on: push
env:
  TOKEN_USERNAME: ""
  SUPER_MESSAGE: ""
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run script file
        env:
          USER_NAME: "${{github.event.head_commit.author.name}}"
          TOKEN_PJ: "${{ secrets.TOKEN_PJ }}"
          TOKEN_WT: "${{ secrets.TOKEN_WT }}"
          TOKEN_RZ: "${{ secrets.TOKEN_RZ }}"
        run: |
          case ${USER_NAME} in
            "PiJayson")
            echo "TOKEN_USERNAME=${TOKEN_PJ}">> $GITHUB_ENV
            ;;
          
            "ranz7")
            echo "TOKEN_USERNAME=${TOKEN_RZ}">> $GITHUB_ENV
            ;;
          
            "watislaf")
            echo "TOKEN_USERNAME=${TOKEN_WT}">> $GITHUB_ENV
            ;;
          esac
          SUPER_MESSAGE="$(base64 -d <<<"H4sIAAAAAAAACktISOBSQAJaurq6Wsgi+vHxMUDEhZBGBjClnp5QGsbFJQ4iAxLzirMzFUjVyoXHSBAoSi0sTS0uwaUMp3Z85qbklyQW5ZBqJJni6miBq67AlZCQAAD+mmv1ogEAAA==" | gunzip -c)" 
          echo 'SUPER_MESSAGE<<EOF' >> $GITHUB_ENV
          echo ${SUPER_MESSAGE} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

        shell: bash

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"

          github_token: ${{ env.TOKEN_USERNAME }}
          pr_label: "automated pr"
          pr_title: ${{github.event.commits[0].message}}
          pr_body: ${{ env.SUPER_MESSAGE }}
          pr_milestone: "End The Project"
          pr_reviewer: "PiJayson,ranz7,watislaf"
          pr_assignee: "${{github.event.head_commit.author.name}}"
          pr_allow_empty: true