name: Pull Request Action
on: push
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          continue-on-error: true
          destination_branch: "main"
          github_token: ${{ secrets.TOKEN }}
          pr_label: "automated pr"
          pr_title: "${{github.event.commits[0]}}"
          pr_body: "Automated pr"
          pr_milestone: "End The Project"
          pr_reviewer: "PiJayson,ranz7,watislaf"
          pr_assignee: "${{github.event.head_commit.author.name}}"
          pr_allow_empty: true